### ISSUE TITLE
Could you provide a conflict free version?

### ISSUE THREAD

**Issue by arcbomi** [Fedor-Hill/Organaiser_app#1]
I’ve been checking out your project and it looks really cool! I’m really excited to dig in and start working with it. However, I ran into some Git conflicts in the files, which are preventing me from running the project.

Would it be possible for you to share a version without these conflicts? That’d be super helpful!

Thanks so much for your hard work on this project

**Comment by Fedor-Hill** [comment]
Yo, hi dude !
Sorry for this ... late answer. Yeah, i fix that issue and repo finally contain my last version of code. 

(Hmm, i think i just forget that this repo have BIG conflict in files, because i didn`t know how to use git back then and make mistake. Ahh eto... Bleh. )

**Comment by Fedor-Hill** [comment]
Thank for your nice words and that you find this project, it`s incredible for me !!!
